### PR TITLE
k8s-mesos no longer requires /api suffix for --server arg

### PR DESCRIPTION
**Pull request by jdef**
remove /api suffix from --server for compliance with v0.7.2 k8s-mesos release

### CODE REVIEW

**Comment by jdef** [comment]
I've tested this against my latest v0.7.2 test image. Works great.

@sttts PTAL

**Comment by sttts** [comment]
lgtm

**Comment by jdef** [comment]
@sttts thanks for the quick review :)  what's the process for release? manually tag and create a GH release via the UI?

**Comment by sttts** [comment]
Exactly. Just create the release in the GH ui and update the subcommand.json.

**Pull request merged**
